# Generated by Django 5.2.5 on 2025-08-15 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('name', 'booking_date')},
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('title', 'price')},
        ),
    ]
